### ISSUE TITLE
object not working

### ISSUE THREAD

**Issue by mamiiiiiii** [mamiiiiiii/Mami_project#2]
hello i'm tried to love you

**Comment by mamiiiiiii** [comment]
i have no answer

**Comment by Dafeurvabene** [comment]
villadest is the best sol

**Comment by mamiiiiiii** [comment]
👍

**Comment by Dafeurvabene** [comment]
rdv

**Comment by Dafeurvabene** [comment]
shbcsj[www.wiki.com]

**Comment by mamiiiiiii** [comment]
@vdsvsvhjkfncdjs,chsuçiodzuqi,[www.google.com](url)`efhbenzfj,kdfnfk,jez`

**Comment by Dafeurvabene** [comment]
[https://openclassrooms.com/forum/sujet/liste-d-erreurs-sous-visual-studio](voir ca)

**Comment by Dafeurvabene** [comment]
[https://openclassrooms.com/forum/sujet/liste-d-erreurs-sous-visual-studio](url) voir ca

**Comment by Dafeurvabene** [comment]
> hhh

**Comment by mamiiiiiii** [comment]
dffdv #

**Comment by Dafeurvabene** [comment]
Dupliquer de # @mamiiiiiii

**Comment by mamiiiiiii** [comment]
dfcdvs
